version: '2'

services:
  phpfpm:
    build: ./.docker/images/php-fpm
    expose:
      - 9000
    volumes:
      - ./.docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./.docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/html

  nginx-app:
    image: nginx
    links:
      - phpfpm
      - db
      - composer
    volumes:
      - ./.docker/images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./.docker/data/mysql/:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql

  composer:
    build: ./.docker/images/composer
    command: install --ignore-platform-reqs
    volumes:
      - ../:/var/www/html

volumes:
  data_volume:

networks:
  default:
    external:
      name: nginx-proxy
