version: '1'

services:
  phpfpm:
    build: ./.docker/images/php-fpm
    volumes:
      - ./.docker/images/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./.docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
  
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.docker/images/proxy/certs:/etc/nginx/certs:ro
      - ./.docker/images/proxy/vhost.d:/etc/nginx/vhost.d
      - ./.docker/images/proxy/html:/usr/share/nginx/html

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/images/proxy/certs:/etc/nginx/certs:rw

  nginx-app:
    image: nginx
    volumes:
      - ./.docker/images/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    environment:
      VIRTUAL_HOST: dc.dev
      LETSENCRYPT_HOST: $LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./.docker/data/mysql/:/docker-entrypoint-initdb.d
      - data_volume:/var/lib/mysql
   
  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - ./app:/app

volumes:
  data_volume:
